import { prisma } from '@/lib/db'
import { notFound } from 'next/navigation'

export default async function PayPage({ params }: { params: { reference: string } }) {
  const link = await prisma.paymentLink.findUnique({
    where: { reference: params.reference },
    include: { business: true, staff: true },
  })

  if (!link) notFound()

  const isExpired = new Date(link.expiresAt) < new Date()
  const isPaid = link.status === 'paid'

  return (
    <main style={{ minHeight: '100vh', background: '#F7F5F0', display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 24, fontFamily: "'DM Sans', sans-serif" }}>
      <div style={{ background: '#fff', borderRadius: 20, padding: '40px 40px', maxWidth: 440, width: '100%', border: '1px solid rgba(0,0,0,0.07)', textAlign: 'center' }}>

        <div style={{ display: 'flex', alignItems: 'center', gap: 10, justifyContent: 'center', marginBottom: 28 }}>
          <div style={{ width: 28, height: 28, background: '#1B4332', borderRadius: 7, display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#fff', fontSize: 14 }}>🔒</div>
          <span style={{ fontFamily: 'Fraunces, serif', fontSize: 18, fontWeight: 500, color: '#1A1A18' }}>LedgerLock</span>
        </div>

        {isPaid ? (
          <>
            <div style={{ fontSize: 44, marginBottom: 12 }}>✅</div>
            <h1 style={{ fontFamily: 'Fraunces, serif', fontSize: 22, fontWeight: 500, margin: '0 0 8px', color: '#1B4332' }}>Payment Confirmed</h1>
            <p style={{ fontSize: 14, color: '#6B6B67' }}>This payment has already been received and verified.</p>
          </>
        ) : isExpired ? (
          <>
            <div style={{ fontSize: 44, marginBottom: 12 }}>⏰</div>
            <h1 style={{ fontFamily: 'Fraunces, serif', fontSize: 22, fontWeight: 500, margin: '0 0 8px', color: '#C0392B' }}>Link Expired</h1>
            <p style={{ fontSize: 14, color: '#6B6B67' }}>This payment link has expired. Please contact {link.business.name} for a new link.</p>
          </>
        ) : (
          <>
            <div style={{ background: '#D8F3DC', borderRadius: 12, padding: '16px', marginBottom: 24 }}>
              <div style={{ fontSize: 11, color: '#2D6A4F', textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: 4 }}>Verified Payment to</div>
              <div style={{ fontFamily: 'Fraunces, serif', fontSize: 20, fontWeight: 500, color: '#1B4332', marginBottom: 2 }}>{link.business.name}</div>
              <div style={{ fontSize: 11, color: '#2D6A4F' }}>🔒 Account verified via Auth0 Token Vault · Cannot be redirected</div>
            </div>

            <div style={{ marginBottom: 24 }}>
              <div style={{ fontFamily: 'Fraunces, serif', fontSize: 36, fontWeight: 500, color: '#1A1A18' }}>₦{link.amount.toLocaleString()}</div>
              <div style={{ fontSize: 14, color: '#6B6B67', marginTop: 4 }}>{link.service}</div>
              <div style={{ fontSize: 12, color: '#9CA3AF', marginTop: 4 }}>Ref: {link.reference}</div>
            </div>

            <a
              href={link.url.startsWith('http') ? link.url : `https://paystack.com/pay/${link.reference}`}
              style={{
                display: 'block', padding: '14px', background: '#1B4332', color: '#fff',
                borderRadius: 10, textDecoration: 'none', fontSize: 15, fontWeight: 600, marginBottom: 16,
              }}
            >
              Pay Now →
            </a>

            <div style={{ fontSize: 11, color: '#9CA3AF', lineHeight: 1.6 }}>
              This link was generated by {link.staff?.name || 'staff'} at {link.business.name}.<br />
              Funds go directly to the business account — not to any individual employee.<br />
              Expires {new Date(link.expiresAt).toLocaleString()}
            </div>
          </>
        )}

        <div style={{ marginTop: 24, paddingTop: 16, borderTop: '1px solid rgba(0,0,0,0.07)', fontSize: 11, color: '#C4C4C0' }}>
          Secured by LedgerLock + Auth0 Token Vault
        </div>
      </div>
    </main>
  )
}
